Master - first_homework
epam-js-jun-2019/html-css-1 pull request #16
Opened 2019-07-11 11:23 UTC by Snabbaspirit

* Added:
  - images;
  - css;
  - font;
  - html;

2019-07-16 20:55 UTC, aleksandrbelik requested changes

2019-07-16 20:55 UTC, aleksandrbelik commented on Ivan_Kuzmin/css/style.css
> +    background: url("../images/back_black.png") no-repeat;
@Snabbaspirit It's better to set shadow by css property

2019-07-16 20:55 UTC, aleksandrbelik commented on Ivan_Kuzmin/css/style.css
> +    background: url("../images/chicago_back.png");
@Snabbaspirit And here is better to use background to set color instead of separate image. This is also cover other selectors like .seattle, .brooklyn, .portland, .week, .san-jose

2019-07-16 20:55 UTC, aleksandrbelik commented on Ivan_Kuzmin/css/style.css
> +    margin-right: -2px;
@Snabbaspirit You don't need to set negative margin if you use background with color instead of background with image

2019-07-16 20:55 UTC, aleksandrbelik commented on Ivan_Kuzmin/css/style.css
> +.city-block_container img {
@Snabbaspirit It's better to set additional class to image
city-block_img or smth like this

2019-07-16 20:55 UTC, aleksandrbelik commented on Ivan_Kuzmin/css/style.css
> +    padding: 40px 8px;
@Snabbaspirit You cal also use flex to align content of city-block_container inside back-cities

2019-07-18 21:33 UTC, Snabbaspirit commented on Ivan_Kuzmin/css/style.css
> +    background: url("../images/back_black.png") no-repeat;
Done

2019-07-18 21:33 UTC, Snabbaspirit commented on Ivan_Kuzmin/css/style.css
> +    background: url("../images/chicago_back.png");
Done

2019-07-18 21:33 UTC, Snabbaspirit commented on Ivan_Kuzmin/css/style.css
> +    margin-right: -2px;
Done

2019-07-18 21:33 UTC, Snabbaspirit commented on Ivan_Kuzmin/css/style.css
> +.city-block_container img {
Done

2019-07-18 21:33 UTC, Snabbaspirit commented on Ivan_Kuzmin/css/style.css
> +    padding: 40px 8px;
Done

2022-12-19 11:04 UTC, closed without merging